apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
  - name: postgres-scraper
    type: postgres
    uid: postgres-scraper
    url: postgres:5432
    user: scraper
    secureJsonData:
      password: scraper123
    jsonData:
      database: scraping
      sslmode: disable
      postgresVersion: 16
